import Head from 'next/head'
                import Image from 'next/image'
                import styles from '../../styles/Home.module.css'
                import Container from 'react-bootstrap/Container';
                import Row from 'react-bootstrap/Row';
                import Col from 'react-bootstrap/Col';
                import 'bootstrap/dist/css/bootstrap.min.css';
                import Card from 'react-bootstrap/Card';
                import CardGroup from 'react-bootstrap/CardGroup';
                import Button  from 'react-bootstrap/Button';
                import tabs  from 'react-bootstrap/Tabs';
                import Tabs from 'react-bootstrap/Tabs';
                import Form from 'react-bootstrap/Form';
                export default function Home() {
                    return (  
                    <div className={styles.container}>
                        <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                        </Head>
                        
                        <Container>
                        <Row>
                            <Col md={3} sm={12} >
                                <div className={styles.box}>
                                <Row>
                                <Col md={4} sm={12}>
                                    <div className={styles.box1}>
                                    <span>
                                    <h1 className={styles.h2}>R</h1>
                                    </span>
                                    </div>
                                </Col>
                                <Col md={8} sm={12}>
                                    <div className={styles.box2}>
                                    <p className={styles.box2p}><b>Rajdeep Singh 0001</b></p>
                                    <p>
                                        Get access to exclusive information and intract with fell auto lovers. 

                                    </p>
                                    <p className={styles.box2p2}>
                                    <Image src="/pic.png" alt="pic3" width="15%" height="15"/><span>Newbie</span>
                                    </p>
                                    <div className={styles.edit}>
                                        <p>joined in 23 aug 2022</p>
                                        <p>Edit</p>
                                    </div>
                                    
                                    </div>
                                
                                </Col>
                                </Row>
                                <hr></hr>
                                <div>
                                    <div>
                                    
                                        <div className={styles.edit}>
                                        <p><b>My Garage </b> </p>
                                        <p className={styles.box2}>Add/Edit</p>
                                    </div>
                                        <h6 className={styles.box2}>&#9679; Maruti Suzuki Swift 2014-2022</h6>

                                    </div>
                                <Row>
                                <Col md={4} sm={12}>
                                    <div className={styles.box1}>
                                    <Image src="/35.jpg" alt="pic3" width="100%" height="100"/>
                                    </div>
                                    
                                </Col>
                                <Col md={8} sm={12}>
                                    <div className={styles.box2}>
                                    <p>
                                    Help Fellow auto lovers by review and answering questions & become a Zigwheels Legend
                                    </p>
                                
                                    
                                    </div>
                                
                                </Col>
                                </Row>
                                </div>
                                </div>
                            </Col>
                        <Col md={9} sm={12} >
                        
                            <div className={styles.tabdiv}>
                            <Card>
                    <Card.Body>
                            <h5> My Activity</h5> 
                                <Tabs>
                                    <Tabs eventKey="home" title="Question For You">
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                        
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                                    <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                            
                                        <p className={styles.h312}><span className={styles.h31}>Lovkush </span> asked about  Maruti Suzuki Swift 2014-2021</p>
                                        <h3 className={styles.h3}>Q. This car CNG variant or not - Swift ?</h3>
                                        <Form.Control className={styles.form_box} type="text" placeholder="Add your answer" />
                                                
                                        <h5 className={styles.h31}>View 4 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                        </Form.Group>
                                    </Form>
                            </Tabs>
                            <Tabs eventKey="profile" title="Answer">
                            <p className={styles.h312}><span className={styles.h31}>Prabhat </span> asked about  Royal Enfield 350 (2014-2021)</p>
                            <h3 className={styles.h3}>Q. What's the minimum hight of a person required to drive clasic 350 ?</h3>
                               <p  className={styles.edit2}> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
                                 </svg><p>Follow Question |</p><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
                                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
                                    </svg>Add Answer</p>
                                    <Row>
                                <Col md={1} sm={12}>
                                <div className={styles.box1}>
                                    <span>
                                    <h1 className={styles.h21}>R</h1>
                                    </span>
                                    </div>
                                    
                                </Col>
                                <Col md={11} sm={12}>
                                    <div className={styles.box2}>
                                        <div className={styles.edit23}>
                                    <p className={styles.h31}>Rajdeep singh</p><p>| 1 month ago</p>
                                    </div>
                                    <div className={styles.triangle}></div>
                                    <div className={styles.ans}><div className={styles.ans2}>@Jatav | are you mad bro if you are ridding bullet with one or two guy.. being let not touch the ground you are gone a suffer to much ..if there will be some holes like dig on the road .. you are gone..5.b is enough ..Read More
                                    </div>Hi</div>
                                    <div className={styles.edit231}>
                                    <div><svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg>| Reply</div><svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                    </svg>
                                    </div>
                                    </div>
                                
                                </Col>
                                </Row>
                                <h5 className={styles.h3122}>View 3 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                <p className={styles.h312}><span className={styles.h31}>Prabhat </span> asked about  Royal Enfield 350 (2014-2021)</p>
                            <h3 className={styles.h3}>Q. What's the minimum hight of a person required to drive clasic 350 ?</h3>
                               <p  className={styles.edit2}> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
                                 </svg><p>Follow Question |</p><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
                                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
                                    </svg>Add Answer</p>
                                    <Row>
                                <Col md={1} sm={12}>
                                <div className={styles.box1}>
                                    <span>
                                    <h1 className={styles.h21}>R</h1>
                                    </span>
                                    </div>
                                    
                                </Col>
                                <Col md={11} sm={12}>
                                    <div className={styles.box2}>
                                        <div className={styles.edit23}>
                                    <p className={styles.h31}>Rajdeep singh</p><p>| 1 month ago</p>
                                    </div>
                                    <div className={styles.triangle}></div>
                                    <div className={styles.ans}><div className={styles.ans2}>@Jatav | are you mad bro if you are ridding bullet with one or two guy.. being let not touch the ground you are gone a suffer to much ..if there will be some holes like dig on the road .. you are gone..5.b is enough ..Read More
                                    </div>Hi</div>
                                    <div className={styles.edit231}>
                                    <div><svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg>| Reply</div><svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                    </svg>
                                    </div>
                                    </div>
                                
                                </Col>
                                </Row>
                                <h5 className={styles.h3122}>View 3 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        
                                <p className={styles.h312}><span className={styles.h31}>Prabhat </span> asked about  Royal Enfield 350 (2014-2021)</p>
                            <h3 className={styles.h3}>Q. What's the minimum hight of a person required to drive clasic 350 ?</h3>
                               <p  className={styles.edit2}> <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
                                 </svg><p>Follow Question |</p><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
                                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
                                    </svg>Add Answer</p>
                                    <Row>
                                <Col md={1} sm={12}>
                                <div className={styles.box1}>
                                    <span>
                                    <h1 className={styles.h21}>R</h1>
                                    </span>
                                    </div>
                                    
                                </Col>
                                <Col md={11} sm={12}>
                                    <div className={styles.box2}>
                                        <div className={styles.edit23}>
                                    <p className={styles.h31}>Rajdeep singh</p><p>| 1 month ago</p>
                                    </div>
                                    <div className={styles.triangle}></div>
                                    <div className={styles.ans}><div className={styles.ans2}>@Jatav | are you mad bro if you are ridding bullet with one or two guy.. being let not touch the ground you are gone a suffer to much ..if there will be some holes like dig on the road .. you are gone..5.b is enough ..Read More
                                    </div>Hi</div>
                                    <div className={styles.edit231}>
                                    <div><svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg>| Reply</div><svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                    </svg>
                                    </div>
                                    </div>
                                
                                </Col>
                                </Row>
                                <h5 className={styles.h3122}>View 3 More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                                        


                        </Tabs>
                        
                        <Tabs eventKey="profil1e" title="Question Asked">
                        
                        </Tabs>
                        <Tabs eventKey="prof3ile" title="Question Followed">
                       
                        </Tabs>
                        <Tabs eventKey="pro3file" title="Your Review">
                        <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                                <Form.Label>Email address</Form.Label>
                                                <Form.Control type="email" placeholder="Enter email" />
                                                <Form.Text className="text-muted">
                                                We'll never share your email with anyone else.
                                                </Form.Text>
                                        </Form.Group>
                                    </Form>
                        </Tabs>
                        <Tabs eventKey="contact" title="Shortlist" >
                        <Form>
                                        <Form.Group className="mb-3" controlId="formBasicEmail">
                                                <Form.Label>Email address</Form.Label>
                                                <Form.Control type="email" placeholder="Enter email" />
                                                <Form.Text className="text-muted">
                                                We'll never share your email with anyone else.
                                                </Form.Text>
                                        </Form.Group>
                                    </Form>
                        </Tabs>
                    </Tabs>

                    </Card.Body>
                </Card>
                        
                </div>
                        </Col>
                        </Row>
                        
                    </Container>
                        <main className={styles.main}>
                        
                    

                        
                        </main>

                        <footer className={styles.footer}>
                        <a
                            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            Powered by{' '}
                            <span className={styles.logo}>
                            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                            </span>
                        </a>
                        </footer>
                    </div>
                    )
                }