import Head from 'next/head'

import 'bootstrap/dist/css/bootstrap.min.css';
import Image from 'next/image'
import styles from '../styles/form2.module.css'
import axios from 'axios';  
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';


export default function Home() {
  

  return (


    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
       <div className={styles.form2}>
           <Form>
           <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Name</Form.Label>
        <Form.Control type="email" placeholder="Enter Name" />
       
      </Form.Group>
           <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Address</Form.Label>
        <Form.Control type="email" placeholder="Enter address" />
       
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Email address</Form.Label>
        <Form.Control type="email" placeholder="Enter email" />
       
      </Form.Group>

      <Form.Group className="mb-3" controlId="formBasicPassword">
        <Form.Label>Password</Form.Label>
        <Form.Control type="password" placeholder="Password" />
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicCheckbox">
        <Form.Check type="checkbox" label="Check me out" />
      </Form.Group>
      <Button className={styles.btm} variant="primary" type="submit">
        Submit
      </Button>
    </Form>
       
    </div> 

    
      </main>

     
    </div>
  );

  }
